# Generated by Django 5.1.15 on 2026-06-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefono'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=20)),
                ('message', models.TextField()),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
