# Generated by Django 5.2.13 on 2026-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_team_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="organization_logo",
            field=models.ImageField(
                blank=True,
                help_text="Imagen opcional. Puede cargarla, sustituirla o marcarla para eliminarla.",
                null=True,
                upload_to="team/members/organizations/",
                verbose_name="Logo de la organización",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="organization_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre que se utilizará para identificar el logo y generar su texto alternativo.",
                max_length=200,
                verbose_name="Nombre de la organización",
            ),
        ),
        migrations.AddConstraint(
            model_name="collaboratingentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 0)),
                name="collaboratingentity_order_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 0)),
                name="teamgroup_order_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 0)),
                name="teammembership_order_non_negative",
            ),
        ),
    ]
