# Generated by Django 5.2.13 on 2026-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_teammember_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalTexts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "legal_notice_es",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introduce el texto completo, con párrafos y saltos de línea. No admite HTML.",
                        verbose_name="Aviso legal — Castellano",
                    ),
                ),
                (
                    "legal_notice_eu",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introduce el texto completo, con párrafos y saltos de línea. No admite HTML.",
                        verbose_name="Aviso legal — Euskera",
                    ),
                ),
                (
                    "legal_notice_published",
                    models.BooleanField(
                        default=False, verbose_name="Aviso legal publicado"
                    ),
                ),
                (
                    "legal_notice_revision_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de revisión del aviso legal",
                    ),
                ),
                (
                    "privacy_es",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introduce el texto completo, con párrafos y saltos de línea. No admite HTML.",
                        verbose_name="Privacidad — Castellano",
                    ),
                ),
                (
                    "privacy_eu",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introduce el texto completo, con párrafos y saltos de línea. No admite HTML.",
                        verbose_name="Privacidad — Euskera",
                    ),
                ),
                (
                    "privacy_published",
                    models.BooleanField(
                        default=False, verbose_name="Privacidad publicada"
                    ),
                ),
                (
                    "privacy_revision_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de revisión de privacidad",
                    ),
                ),
                (
                    "cookies_es",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introduce el texto completo, con párrafos y saltos de línea. No admite HTML.",
                        verbose_name="Cookies — Castellano",
                    ),
                ),
                (
                    "cookies_eu",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introduce el texto completo, con párrafos y saltos de línea. No admite HTML.",
                        verbose_name="Cookies — Euskera",
                    ),
                ),
                (
                    "cookies_published",
                    models.BooleanField(
                        default=False, verbose_name="Cookies publicadas"
                    ),
                ),
                (
                    "cookies_revision_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de revisión de cookies",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Textos legales",
                "verbose_name_plural": "Textos legales",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton", True)),
                        name="legaltexts_singleton_must_be_true",
                    )
                ],
            },
        ),
    ]
